# config_cpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-highmem-2
    replicaCount: 1
    containerSpec:
        imageUri: IMAGE_URI
        env:
        - name: STORAGE_URI
          value: STORAGE_URI
        - name: CONFIG_NAME
          value: CONFIG_NAME
        command: ["bash"]
        args: ["-c", "chmod +x gcloud_container_command.sh && ./gcloud_container_command.sh"]

