steps:
- name: 'alpine'
  id: 'Replace values in the training config'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      apk add --no-cache gettext
      envsubst < vertex_config/config_gpu.yaml > config_gpu.yaml.tmp
      mv config_gpu.yaml.tmp config_gpu.yaml
  secretEnv: ['WANDB_API_KEY', 'GITHUB_TOKEN']

- name: 'alpine'
  id: 'Show config'
  waitFor: ['Replace values in the training config']
  entrypoint: "sh"
  args:
    - '-c'
    - |
      cat config_gpu.yaml

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Train on vertex AI'
  waitFor: ['Replace values in the training config']
  args: [
    'ai',
    'custom-jobs',
    'create',
    '--region',
    'europe-west4',
    '--display-name',
    'gpu-training-job',
    '--enable-web-access',
    '--service-account',
    'vertex-manager@pet-fac-rec.iam.gserviceaccount.com',
    '--config',
    '${_VERTEX_TRAIN_CONFIG}',
  ]

substitutions:
  _VERTEX_TRAIN_CONFIG: 'config_gpu.yaml'
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/WANDB_API_KEY/versions/latest
    env: 'WANDB_API_KEY'
  - versionName: projects/$PROJECT_ID/secrets/GITHUB_TOKEN/versions/latest
    env: 'GITHUB_TOKEN'

