name: DVC Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/data.dvc'
      - '.dvc/**'
# REMOVE LATER
  push:
    branches:
      - gcloud
    paths:
      - '**/data.dvc'
      - '.dvc/**'

jobs:
  dataset_statistics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            requirements_dev.txt
            requirements_tests.txt

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
          pip install -r requirements_tests.txt
          pip list

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.BUCKET_DVC_MANAGER_KEY }}

      - name: Pull data
        run: |
          dvc pull ./data --no-run-cache

      - name: Check data statistics
        run: |
          python src/pet_fac_rec/data.dataset_statistics.py

      - name: Check data statistics & generate report
        run: |
          python src/pet_fac_rec/data.dataset_statistics.py > data_statistics.md
          echo '![](./pet_facial_expressions.png "Pet facial expressions")' >> data_statistics.md
          echo '![](./train_label_distribution.png "Train label distribution")' >> data_statistics.md
          echo '![](./test_label_distribution.png "Test label distribution")' >> data_statistics.md

      - name: Setup cml
        uses: iterative/setup-cml@v2

      - name: Comment on PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create data_statistics.md --watermark-title="Data Checker" # (1)!