name: Lint

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            requirements_dev.txt
            requirements_tests.txt

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install pylint
          pip install -r requirements.txt

      - name: Run pylint
        run: |
          pylint src/ tests/ --fail-under=8.0
